driver: Makefile: Ignore -Wswitch
That is required to bypass such issues:
kernel/amlogic/linux-4.9/../kernel-modules/linux_openvfd/driver/openvfd_drv.c:445:8: error: overflow converting case value to switch condition type (2147765512 to 18446744071562349832) [-Werror,-Wswitch]